# This starts two services
# The first is called "web" and uses the Dockerfile in the ./web directory
# Port 7555 on the real machine forwards to Port 5000 in the "web" container

# The second service is called "api" and uses the Dockerfile in ./api
# This service exposes port 5000 to other docker container machines
# ... However, no ports are available to the real machine

services:
    web:
        build: ./web
        links:
          - db
        ports:
          - "7555:5000"
    api:
        build: ./api
        expose: #only available to the other images
          - "5000"
    db:
        build: ./tests
        restart: always
        ports:
          - "6600:6600"
